apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-study-notification-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-study-notification
  template:
    metadata:
      labels:
        app: backend-study-notification
    spec:
      containers:
        - name: backend-study-notification
          image: nebulaesthetic/studyhub-study-notification:0.0.1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: notification-configmap
              readOnly: true
            - mountPath: /etc/mysql
              name: mysql-jdbc-secret
              readOnly: true
            - mountPath: /etc/kafka
              name: kafka-secret
              readOnly: true
      volumes:
        - name: notification-configmap
          configMap:
            name: notification-configmap
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: mysql-jdbc-secret
          secret:
            secretName: mysql-jdbc-secret-volume
            items:
              - key: application-mysql.yml
                path: application-mysql.yml
        - name: kafka-secret
          secret:
            secretName: kafka-secret-volume
            items:
              - key: kafka.yaml
                path: application-kafka.yml