apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
data:
  application-dev.yml: |
    server:
      port: 8080
    spring:
      datasource:
        url: jdbc:mysql://39.118.81.100:30082/notification_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: user
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          connection-test-query: SELECT 1
          validation-timeout: 5000
      jpa:
        hibernate:
          ddl-auto: update
        generate-ddl: true
        show-sql: true
        open-in-view: false